class CompanyIncorporationErrorCode:
    WORKSPACE_NOT_FOUND = "COMPANY_INCORPORATION_WORKSPACE_NOT_FOUND"
    WORKSPACE_VERSION_CONFLICT = "COMPANY_INCORPORATION_VERSION_CONFLICT"
    VALIDATION_FAILED = "COMPANY_INCORPORATION_VALIDATION_FAILED"
    ONBOARDING_NOT_SUBMITTED = "ONBOARDING_NOT_SUBMITTED"
