from enum import StrEnum


class OnboardingErrorCode(StrEnum):
    ONBOARDING_NOT_FOUND = "ONBOARDING_NOT_FOUND"
    ONBOARDING_FORBIDDEN = "ONBOARDING_FORBIDDEN"
    ONBOARDING_ALREADY_SUBMITTED = "ONBOARDING_ALREADY_SUBMITTED"
    ONBOARDING_VALIDATION_ERROR = "ONBOARDING_VALIDATION_ERROR"
    ONBOARDING_INCOMPLETE = "ONBOARDING_INCOMPLETE"
