import type {
  DeclarationDetail,
  FinancialYearRow,
  IpoSetupPayload,
} from '@/lib/schemas/ipo-setup';
import { IPO_SETUP_SCHEMA_VERSION } from '@/lib/schemas/ipo-setup';

export function createEmptyDeclarationDetail(id?: string): DeclarationDetail {
  return {
    id: id ?? crypto.randomUUID(),
    personOrEntityInvolved: '',
    authorityOrForum: '',
    date: '',
    currentStatus: '',
    explanation: '',
  };
}

export function createEmptyFinancialYearRow(id?: string): FinancialYearRow {
  return {
    id: id ?? crypto.randomUUID(),
    financialYearEnding: '',
    operatingProfitFromOperations: null,
    netWorth: null,
    freeCashFlowToEquity: null,
    auditedStatus: '',
    sourceType: '',
  };
}

export function createEmptyIpoSetupPayload(): IpoSetupPayload {
  return {
    schemaVersion: IPO_SETUP_SCHEMA_VERSION,
    ipoDirection: {
      preparationStage: '',
      targetSmePlatform: '',
      eligibilityProfile: '',
      proposedOfferType: '',
      proposedPricingMethod: '',
      targetFilingQuarter: '',
      targetFilingFinancialYear: '',
      tentativeFilingDate: '',
      targetListingPeriod: '',
      referencedCompanyClass: '',
      publicCompanyConversionStatus: '',
      proposedConversionDate: '',
      actualConversionDate: '',
      newLegalNameAfterConversion: '',
      conversionSrnOrReference: '',
      freshCertificateOfIncorporationAvailable: '',
    },
    offerStructure: {
      amountDisplayUnit: 'crore',
      faceValuePerEquityShare: null,
      existingIssuedEquityShares: null,
      existingPaidUpEquityShareCapital: null,
      proposedIssuePriceStatus: '',
      proposedIssuePrice: null,
      proposedFreshIssueShares: null,
      proposedFreshIssueAmount: null,
      preIpoPlacementBeingConsidered: '',
      proposedPreIpoPlacementAmount: null,
      proposedOfsShares: null,
      proposedOfsAmount: null,
      numberOfSellingShareholders: null,
      sellerConsentsObtained: '',
      employeeReservationPlanned: '',
      existingShareholderReservationPlanned: '',
      marketMakerReservationStatus: '',
      otherReservationNotes: '',
    },
    trackRecordAndFinancialEligibility: {
      operatingTrackRecordBasis: '',
      trackRecordEntityName: '',
      natureOfEntity: '',
      sameLineOfBusiness: '',
      businessCommencementDate: '',
      conversionOrSuccessionDate: '',
      relationshipToIssuer: '',
      threeCompleteFinancialYearsAvailable: '',
      auditedRecordsAvailable: '',
      continuityExplanation: '',
      financialYears: [
        createEmptyFinancialYearRow(),
        createEmptyFinancialYearRow(),
        createEmptyFinancialYearRow(),
      ],
      latestAuditedFinancialYear: '',
      latestFinancialStatementsAvailable: '',
      stubPeriodFinancialsAvailable: '',
      auditorHasConfirmedEligibilityFigures: '',
      modifiedAuditOpinionRelevantToEligibility: '',
      modifiedAuditOpinionExplanation: '',
    },
    eligibilityDeclarations: {
      admittedIbcAgainstIssuer: '',
      admittedIbcAgainstIssuerDetails: [],
      admittedIbcAgainstPromotingCompany: '',
      admittedIbcAgainstPromotingCompanyDetails: [],
      admittedWindingUpPetition: '',
      admittedWindingUpPetitionDetails: [],
      issuerDebarredFromCapitalMarkets: '',
      issuerDebarredFromCapitalMarketsDetails: [],
      promoterDirectorSellingShareholderDebarred: '',
      promoterDirectorSellingShareholderDebarredDetails: [],
      promoterDirectorAssociatedWithDebarredCompany: '',
      promoterDirectorAssociatedWithDebarredCompanyDetails: [],
      wilfulDefaulterOrFraudulentBorrower: '',
      wilfulDefaulterOrFraudulentBorrowerDetails: [],
      fugitiveEconomicOffender: '',
      fugitiveEconomicOffenderDetails: [],
      materialRegulatoryOrDisciplinaryAction: '',
      materialRegulatoryOrDisciplinaryActionDetails: [],
      seriousCriminalProceedingsInvolvingDirector: '',
      seriousCriminalProceedingsInvolvingDirectorDetails: [],
      materialFinancialDefaultDuringRelevantPeriod: '',
      materialFinancialDefaultDuringRelevantPeriodDetails: [],
      materialUnresolvedEligibilityLitigation: '',
      materialUnresolvedEligibilityLitigationDetails: [],
      proceedsIncludeRelatedPartyLoanRepayment: '',
      proceedsIncludeRelatedPartyLoanRepaymentDetails: [],
    },
    processReadiness: {
      boardApprovalStatus: '',
      boardResolutionDate: '',
      boardResolutionReference: '',
      shareholderApprovalStatus: '',
      shareholderResolutionDate: '',
      shareholderResolutionReference: '',
      existingSharesFullyDematerialised: '',
      isinAllotted: '',
      nsdlConnectivityStatus: '',
      cdslConnectivityStatus: '',
      rtaArrangementsInitiated: '',
      leadManagerAppointmentStatus: '',
      registrarAppointmentStatus: '',
      marketMakerAppointmentStatus: '',
      underwriterAppointmentStatus: '',
      legalAdviserAppointmentStatus: '',
      statutoryAuditorCoordinationStatus: '',
      inPrincipleApplicationStatus: '',
      inPrincipleApplicationDate: '',
      inPrincipleApplicationReference: '',
      clarificationsReceived: '',
      inPrincipleApprovalReceived: '',
      inPrincipleApprovalDate: '',
      inPrincipleApprovalReference: '',
    },
    issuerConfirmations: {
      offerInputsAreLatestInternalProposal: false,
      financialFiguresTraceableToSelectedSource: false,
      knownEligibilityConcernsDisclosed: false,
      missingAnswersMustNotBeInterpretedAsNegative: false,
      proposedOfsIncludesAllIntendedSellingShareholders: false,
      assessmentIsPreliminary: false,
      professionalAndExchangeConfirmationRemainRequired: false,
    },
  };
}
