import { QuestionnaireSection, Question } from "./types";

export const questionnaireSections: QuestionnaireSection[] = [
  {
    id: "company-overview",
    title: "Company Overview",
    description: "Provide basic information about your company",
    questions: [
      {
        id: "q1",
        sectionId: "company-overview",
        question: "What is the principal business activity of your company?",
        type: "textarea",
        required: true,
        placeholder: "Describe the main business operations",
      },
      {
        id: "q2",
        sectionId: "company-overview",
        question: "What are your main products or services?",
        type: "textarea",
        required: true,
        placeholder: "List key products/services",
      },
      {
        id: "q3",
        sectionId: "company-overview",
        question: "Does your company operate across multiple segments?",
        type: "radio",
        options: ["Yes", "No"],
        required: true,
      },
      {
        id: "q4",
        sectionId: "company-overview",
        question: "List your business segments:",
        type: "textarea",
        required: false,
        placeholder: "If applicable, describe each segment",
      },
    ],
    completedQuestions: 0,
  },
  {
    id: "financial-performance",
    title: "Financial Performance",
    description: "Details about your company's financial metrics",
    questions: [
      {
        id: "q5",
        sectionId: "financial-performance",
        question: "What was your total revenue (turnover) for FY 2023-24?",
        type: "number",
        required: true,
        placeholder: "Enter in INR",
      },
      {
        id: "q6",
        sectionId: "financial-performance",
        question: "What was your profit after tax (PAT) for FY 2023-24?",
        type: "number",
        required: true,
        placeholder: "Enter in INR",
      },
      {
        id: "q7",
        sectionId: "financial-performance",
        question: "What were your total assets as of 31st March 2024?",
        type: "number",
        required: true,
        placeholder: "Enter in INR",
      },
      {
        id: "q8",
        sectionId: "financial-performance",
        question: "What was your EBITDA for FY 2023-24?",
        type: "number",
        required: false,
        placeholder: "Enter in INR (optional)",
      },
      {
        id: "q9",
        sectionId: "financial-performance",
        question: "Are your financials audited by a statutory auditor?",
        type: "radio",
        options: ["Yes", "No"],
        required: true,
      },
    ],
    completedQuestions: 0,
  },
  {
    id: "governance-compliance",
    title: "Governance & Compliance",
    description: "Information about board composition and regulatory compliance",
    questions: [
      {
        id: "q10",
        sectionId: "governance-compliance",
        question: "Provide details of all Board Members:",
        type: "textarea",
        required: true,
        placeholder: "Name, designation, qualifications for each member",
      },
      {
        id: "q11",
        sectionId: "governance-compliance",
        question: "Does your company have an Audit Committee?",
        type: "radio",
        options: ["Yes", "No"],
        required: true,
      },
      {
        id: "q12",
        sectionId: "governance-compliance",
        question: "List any material litigation or regulatory actions:",
        type: "textarea",
        required: false,
        placeholder: "Describe any pending cases or regulatory matters",
      },
      {
        id: "q13",
        sectionId: "governance-compliance",
        question: "Have you complied with all applicable Indian regulations?",
        type: "radio",
        options: ["Yes", "No", "Partially"],
        required: true,
      },
    ],
    completedQuestions: 0,
  },
  {
    id: "risk-management",
    title: "Risk Management & Strategy",
    description: "Your approach to risks and business strategy",
    questions: [
      {
        id: "q14",
        sectionId: "risk-management",
        question: "Identify the key risks facing your business:",
        type: "textarea",
        required: true,
        placeholder: "List market, operational, financial risks, etc.",
      },
      {
        id: "q15",
        sectionId: "risk-management",
        question: "What are your mitigation strategies?",
        type: "textarea",
        required: true,
        placeholder: "Explain how you manage each identified risk",
      },
      {
        id: "q16",
        sectionId: "risk-management",
        question: "What is your 3-5 year growth strategy?",
        type: "textarea",
        required: true,
        placeholder: "Outline your expansion and growth plans",
      },
      {
        id: "q17",
        sectionId: "risk-management",
        question: "What are your capital expenditure plans for the next 3 years?",
        type: "number",
        required: true,
        placeholder: "Enter total CAPEX in INR",
      },
    ],
    completedQuestions: 0,
  },
  {
    id: "use-of-funds",
    title: "Use of IPO Proceeds",
    description: "How you plan to utilize IPO funds",
    questions: [
      {
        id: "q18",
        sectionId: "use-of-funds",
        question: "What is the target IPO size (in INR crores)?",
        type: "number",
        required: true,
        placeholder: "Enter target IPO size",
      },
      {
        id: "q19",
        sectionId: "use-of-funds",
        question: "What percentage will be for debt repayment?",
        type: "number",
        required: true,
        placeholder: "Enter percentage",
      },
      {
        id: "q20",
        sectionId: "use-of-funds",
        question: "What percentage will be for capital expenditure?",
        type: "number",
        required: true,
        placeholder: "Enter percentage",
      },
      {
        id: "q21",
        sectionId: "use-of-funds",
        question: "What percentage will be for working capital?",
        type: "number",
        required: true,
        placeholder: "Enter percentage",
      },
      {
        id: "q22",
        sectionId: "use-of-funds",
        question: "Provide detailed use-of-funds breakdown:",
        type: "textarea",
        required: true,
        placeholder: "Detail each allocation category",
      },
    ],
    completedQuestions: 0,
  },
];

export const requiredDocuments = [
  {
    id: "doc1",
    name: "Audited Financial Statements",
    category: "Financial",
    description: "Last 3 years of audited financial statements",
    required: true,
  },
  {
    id: "doc2",
    name: "Board Resolution",
    category: "Governance",
    description: "Board resolution approving IPO",
    required: true,
  },
  {
    id: "doc3",
    name: "Memorandum of Association",
    category: "Legal",
    description: "MOA of the company",
    required: true,
  },
  {
    id: "doc4",
    name: "Articles of Association",
    category: "Legal",
    description: "AOA of the company",
    required: true,
  },
  {
    id: "doc5",
    name: "Director ID Proof",
    category: "Governance",
    description: "ID proof of all directors",
    required: true,
  },
  {
    id: "doc6",
    name: "Corporate Governance Certificate",
    category: "Compliance",
    description: "Certificate confirming CG compliance",
    required: false,
  },
];

export const drhpGapCheckItems = [
  {
    section: "Company Overview",
    items: [
      "Business description must be detailed and specific",
      "All business segments must be clearly defined",
      "Risk factors must be comprehensively listed",
    ],
  },
  {
    section: "Financial Performance",
    items: [
      "Audited financials required for last 3 FYs",
      "Proper accounting standards compliance",
      "Revenue recognition policies must be disclosed",
    ],
  },
  {
    section: "Governance & Compliance",
    items: [
      "Board composition must meet SEBI guidelines",
      "Independent directors requirement",
      "Audit committee mandatory",
      "No material defaults or litigation",
    ],
  },
  {
    section: "Risk Management",
    items: [
      "Comprehensive risk identification required",
      "Mitigation strategies for each risk",
      "Market risk analysis",
      "Regulatory risk assessment",
    ],
  },
  {
    section: "Use of Funds",
    items: [
      "Clear allocation of IPO proceeds",
      "Timing of fund utilization",
      "Expected financial impact",
      "Contingency plans",
    ],
  },
];
