from app.modules.onboarding.sme.step_mappings import DOCUMENT_IDS


def empty_draft_data() -> dict:
    return {
        "roleAuthority": {
            "designation": "",
            "relationship": "",
            "relationshipOther": "",
            "authorisedSignatory": "",
            "basisOfAuthority": "",
            "basisOfAuthorityOther": "",
            "primaryOnboardingContact": "",
            "addAlternateContact": False,
            "alternateContact": {
                "fullName": "",
                "designation": "",
                "email": "",
                "mobile": "",
            },
        },
        "companyIdentity": {
            "legalName": "",
            "cin": "",
            "incorporationDate": "",
            "companyClass": "",
            "registeredState": "",
            "registrarOfCompanies": "",
            "registeredOffice": {
                "addressLine1": "",
                "addressLine2": "",
                "locality": "",
                "city": "",
                "district": "",
                "state": "",
                "pinCode": "",
                "country": "India",
            },
            "companyEmail": "",
            "companyWebsite": "",
        },
        "businessClassification": {
            "primaryIndustry": "",
            "primaryIndustryOther": "",
            "businessSector": "",
            "operationsDescription": "",
            "pan": "",
            "gstRegistrationRequired": "",
            "gstRegistrations": [],
            "udyamRegistration": "",
            "importExportCode": "",
            "employeeCountRange": "",
        },
        "ownershipSnapshot": {
            "promoterCount": "",
            "directorCount": "",
            "promoterHoldingPercent": "",
            "nonPromoterHoldingPercent": "",
            "institutionalShareholdersPresent": "",
            "foreignShareholdersPresent": "",
            "promoterGroupEntitiesPresent": "",
        },
        "ipoIntent": {
            "proposedIssueType": "",
            "issueSizeCrore": "",
            "issueSizeNotDecided": False,
            "targetTimeline": "",
            "intendedExchange": "",
            "primaryPurposes": [],
            "primaryPurposeOther": "",
            "merchantBankerAppointed": "",
            "merchantBankerName": "",
            "preparationStage": "",
        },
        "initialDocuments": {
            "selections": {document_id: None for document_id in DOCUMENT_IDS},
            "skippedForNow": False,
        },
        "submissionConfirmations": {
            "confirmAccuracy": False,
            "confirmAuthorised": False,
            "confirmVerification": False,
            "agreeTerms": False,
        },
    }
