INDIAN_STATES_AND_UTS: tuple[str, ...] = (
    "Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
)

REGISTRAR_OF_COMPANIES_OPTIONS: tuple[str, ...] = (
    "Registrar of Companies, Ahmedabad",
    "Registrar of Companies, Bangalore",
    "Registrar of Companies, Chandigarh",
    "Registrar of Companies, Chennai",
    "Registrar of Companies, Coimbatore",
    "Registrar of Companies, Cuttack",
    "Registrar of Companies, Delhi",
    "Registrar of Companies, Ernakulam",
    "Registrar of Companies, Goa",
    "Registrar of Companies, Gwalior",
    "Registrar of Companies, Guwahati",
    "Registrar of Companies, Hyderabad",
    "Registrar of Companies, Jaipur",
    "Registrar of Companies, Kanpur",
    "Registrar of Companies, Kolkata",
    "Registrar of Companies, Mumbai",
    "Registrar of Companies, Patna",
    "Registrar of Companies, Pune",
    "Registrar of Companies, Ranchi",
    "Registrar of Companies, Shillong",
    "Registrar of Companies, Vijayawada",
    "Other / Not listed",
)
