"""Empty-record factories for Intermediaries & Filing (IF1)."""

from __future__ import annotations

from copy import deepcopy
from typing import Any
from uuid import uuid4

from app.modules.intermediaries_filing.constants import SCHEMA_VERSION


def _new_id(id_: str | None = None) -> str:
    return id_ or str(uuid4())


_EMPTY_PAYLOAD: dict[str, Any] = {'depositoriesBankingAsbaUpiAndIssueInfrastructure': {'asbaConfiguration': {'asbaApplicable': '',
                                                                            'bidCollectionConfigurationReviewed': '',
                                                                            'bidCumApplicationFormReady': '',
                                                                            'electronicApplicationReadiness': '',
                                                                            'investorCategoryHandlingReviewed': '',
                                                                            'issueMethod': '',
                                                                            'panDematBankValidationFlowReviewed': '',
                                                                            'professionalConfirmation': '',
                                                                            'registrarReconciliationProcessReady': '',
                                                                            'technicalRejectionCriteriaReviewed': '',
                                                                            'upiMechanismApplicable': ''},
                                                      'depositoryAgreements': {'cdsl': {'agreementDate': '',
                                                                                        'agreementExists': '',
                                                                                        'amendmentRequired': '',
                                                                                        'current': '',
                                                                                        'depository': '',
                                                                                        'issuer': '',
                                                                                        'notes': '',
                                                                                        'reference': '',
                                                                                        'registrarIntermediaryId': ''},
                                                                               'nsdl': {'agreementDate': '',
                                                                                        'agreementExists': '',
                                                                                        'amendmentRequired': '',
                                                                                        'current': '',
                                                                                        'depository': '',
                                                                                        'issuer': '',
                                                                                        'notes': '',
                                                                                        'reference': '',
                                                                                        'registrarIntermediaryId': ''}},
                                                      'depositoryReadiness': {'cdslConnectivityStatus': '',
                                                                              'corporateActionReadiness': '',
                                                                              'existingSpecifiedSecuritiesDematerialisationReadiness': '',
                                                                              'isin': '',
                                                                              'isinStatus': '',
                                                                              'newTemporaryIsinRequirement': '',
                                                                              'nsdlConnectivityStatus': '',
                                                                              'professionalConfirmation': '',
                                                                              'promoterHoldingsDematerialisedStatus': '',
                                                                              'registrarConnectivityStatus': ''},
                                                      'issueBankRoles': [],
                                                      'sponsorBankUpiReadiness': {'agreementExecuted': '',
                                                                                  'contingencyProcess': '',
                                                                                  'escalationContact': '',
                                                                                  'exchangeConnectivityConfirmed': '',
                                                                                  'intermediaryId': '',
                                                                                  'npciReadinessConfirmed': '',
                                                                                  'operationalContact': '',
                                                                                  'professionalConfirmation': '',
                                                                                  'sponsorBankAppointed': '',
                                                                                  'testCompleted': '',
                                                                                  'testDate': '',
                                                                                  'upiSetupComplete': ''}},
 'dueDiligenceCertificatesConsentsAndSignoffs': {'certificates': [],
                                                 'chapterSignoffs': [],
                                                 'consents': [],
                                                 'dueDiligenceAreas': []},
 'filingAndRegulatoryMilestoneTracker': {'exchangeDraftFiling': {'applicationAccepted': '',
                                                                 'checklistVersion': '',
                                                                 'completenessConfirmation': '',
                                                                 'draftFilingDate': '',
                                                                 'exchange': '',
                                                                 'feePaymentReference': '',
                                                                 'feesPaid': '',
                                                                 'filingAcknowledgement': '',
                                                                 'filingChecklistSubmitted': '',
                                                                 'initialQueryDate': '',
                                                                 'notes': '',
                                                                 'vettingReviewStarted': ''},
                                         'exchangeQueries': [],
                                         'filings': [],
                                         'inPrincipleApproval': {'applicationDate': '',
                                                                 'applied': '',
                                                                 'approvalLetterDate': '',
                                                                 'approvalReceived': '',
                                                                 'approvalReference': '',
                                                                 'conditions': '',
                                                                 'conditionsSatisfied': '',
                                                                 'exchange': '',
                                                                 'nameUsePermissionStatus': '',
                                                                 'notes': '',
                                                                 'outstandingConditions': '',
                                                                 'professionalConfirmation': '',
                                                                 'validityDate': ''},
                                         'resubmissions': [],
                                         'rocFiling': {'applicableConsentsIncluded': '',
                                                       'boardApprovalStatus': '',
                                                       'documentType': '',
                                                       'filingComplete': '',
                                                       'filingDate': '',
                                                       'filingRecordId': '',
                                                       'finalSignedVersion': '',
                                                       'formReferenceSrn': '',
                                                       'notes': '',
                                                       'professionalLegalReview': '',
                                                       'registrationAcknowledgement': '',
                                                       'registrationDate': '',
                                                       'requiredAttachmentsIncluded': '',
                                                       'rocJurisdiction': '',
                                                       'shareholderAuthorityReference': ''},
                                         'sebiSmeFiling': {'displayedOnIssuerWebsite': '',
                                                           'displayedOnLeadManagerWebsite': '',
                                                           'displayedOnSebiWebsite': '',
                                                           'displayedOnSmeExchangeWebsite': '',
                                                           'documentVersion': '',
                                                           'dueDiligenceCertificateIncluded': '',
                                                           'filedThroughLeadManager': '',
                                                           'filingApplicability': '',
                                                           'filingDate': '',
                                                           'filingReferenceNumber': '',
                                                           'linkedFilingId': '',
                                                           'professionalConfirmation': '',
                                                           'smeAdditionalConfirmationFormHIncluded': '',
                                                           'status': ''}},
 'finalOfferDocumentAdvertisementsMaterialDocumentsAndFilingReadiness': {'audiovisualPresentation': {'applicability': '',
                                                                                                     'contentApproved': '',
                                                                                                     'englishAvReady': '',
                                                                                                     'hindiAvReady': '',
                                                                                                     'leadManagerApproval': '',
                                                                                                     'linkedOfferDocumentVersionId': '',
                                                                                                     'professionalConfirmation': '',
                                                                                                     'publicationPlatformReference': '',
                                                                                                     'published': ''},
                                                                         'finalConfirmations': {'applicableIntermediaryRegistrationsReviewed': '',
                                                                                                'applicableIssueAgreementsExecutedCurrent': '',
                                                                                                'applicableMarketMakingPeriodAddressed': '',
                                                                                                'applicableProfessionalCertificatesCurrent': '',
                                                                                                'applicableSmeUnderwritingCoverageReviewed': '',
                                                                                                'applicableT3ExecutionPlanReviewed': '',
                                                                                                'auditorsCertifyingProfessionalsEngaged': '',
                                                                                                'bacMattersReconcile': '',
                                                                                                'capitalStructureReconcilesWithCapital': '',
                                                                                                'ddCertificatesCurrent': '',
                                                                                                'depositoryArrangementsReady': '',
                                                                                                'exchangeFilingChecklistComplete': '',
                                                                                                'finalInspectionListReviewed': '',
                                                                                                'finalProfessionalLeadManagerLegalAuditorReviewRemainsRequired': '',
                                                                                                'financialsReconcile': '',
                                                                                                'groupEntitiesReconcile': '',
                                                                                                'inPrincipleApprovalStatusAccuratelyShown': '',
                                                                                                'interSeResponsibilitiesDocumentedWhereNeeded': '',
                                                                                                'intermediaryExpertConsentsCurrent': '',
                                                                                                'isinReady': '',
                                                                                                'issueBankingArrangementsReady': '',
                                                                                                'issueStructureReconcilesWithIpoSetup': '',
                                                                                                'lacUpdatedThroughFilingCutOff': '',
                                                                                                'leadManagerAppointedCurrent': '',
                                                                                                'legalCounselAppointedCurrent': '',
                                                                                                'managementDataReconcile': '',
                                                                                                'marketMakerAppointed': '',
                                                                                                'marketMakingAgreementExecuted': '',
                                                                                                'materialDevelopmentsReviewed': '',
                                                                                                'merchantBankerOwnAccountRequirementReviewed': '',
                                                                                                'noCriticalFilingItemIntentionallyOmitted': '',
                                                                                                'nominatedInvestorArrangementsDisclosedWhereApplicable': '',
                                                                                                'objectsReconcile': '',
                                                                                                'openExchangeQueriesAccuratelyShown': '',
                                                                                                'publicCommunicationsReadinessReviewed': '',
                                                                                                'registrarAppointedCurrent': '',
                                                                                                'rocFilingReadinessReviewed': '',
                                                                                                'sebiSmeFilingStatusAccuratelyShown': '',
                                                                                                'sponsorBankReady': '',
                                                                                                'underwritingArrangementComplete': '',
                                                                                                'unresolvedPlaceholdersAccuratelyShown': ''},
                                                                         'inspectionItems': [],
                                                                         'issueAgreements': [],
                                                                         'merchantBankerDdRepositoryReadiness': {'businessDocsComplete': '',
                                                                                                                 'capitalDocsComplete': '',
                                                                                                                 'companyIncorporationDocsComplete': '',
                                                                                                                 'completionDate': '',
                                                                                                                 'financialDocsComplete': '',
                                                                                                                 'legalDocsComplete': '',
                                                                                                                 'missingRepositoryItems': '',
                                                                                                                 'otherRequiredDdSetsComplete': '',
                                                                                                                 'professionalConfirmation': '',
                                                                                                                 'repositoryRequirementReviewed': '',
                                                                                                                 'responsibleLeadManagerIntermediaryId': '',
                                                                                                                 'uploadComplete': '',
                                                                                                                 'uploadProcessStarted': ''},
                                                                         'offerDocumentVersions': [],
                                                                         'placeholders': [],
                                                                         'publicCommunications': []},
 'issueConfigurationAndFilingSnapshot': {'capitalLinkedSnapshot': {'freshIssueShares': '',
                                                                   'lockInRelatedContext': '',
                                                                   'ofsShares': '',
                                                                   'postIssuePaidUpCapital': '',
                                                                   'postIssueShares': '',
                                                                   'preIssuePaidUpCapital': '',
                                                                   'preIssueShares': '',
                                                                   'promoterContribution': '',
                                                                   'sellingShareholders': ''},
                                         'filingSnapshot': {'additionalExchange': '',
                                                            'capitalStructureFrozen': '',
                                                            'currentOfferDocumentForm': '',
                                                            'filingStage': '',
                                                            'financialsPeriodFrozen': '',
                                                            'issueMethodConfirmed': '',
                                                            'issueStructureFrozen': '',
                                                            'legalDdCutOffFrozen': '',
                                                            'objectsFrozen': '',
                                                            'offerDocumentCutOffDate': '',
                                                            'selectedDesignatedStockExchange': '',
                                                            'snapshotDate': ''},
                                         'filingSnapshotReconciliation': {'discrepancyNote': '',
                                                                          'filingConfirmationStatus': '',
                                                                          'freshIssueAmount': '',
                                                                          'freshIssueShares': '',
                                                                          'marketMakerReservation': '',
                                                                          'netIssueToPublic': '',
                                                                          'ofsAmount': '',
                                                                          'ofsShares': '',
                                                                          'postIssueCapital': '',
                                                                          'postIssueShares': '',
                                                                          'professionalConfirmation': '',
                                                                          'totalOfferAmount': '',
                                                                          'totalOfferShares': ''},
                                         'investorAllocations': [],
                                         'ipoSetupLinkedSnapshot': {'faceValue': '',
                                                                    'floorCapPrice': '',
                                                                    'freshIssue': '',
                                                                    'issueMethod': '',
                                                                    'issueStage': '',
                                                                    'offerSize': '',
                                                                    'ofs': '',
                                                                    'preIpoPlacement': '',
                                                                    'priceBand': '',
                                                                    'proposedFinalIssuePrice': '',
                                                                    'publicCompanyConversionStatus': '',
                                                                    'reservations': '',
                                                                    'targetFilingDate': '',
                                                                    'targetSmePlatform': '',
                                                                    'totalOffer': ''},
                                         'lotApplicationDetails': {'bidMultiples': '',
                                                                   'cutOffPricePermitted': '',
                                                                   'exchangeValidationStatus': '',
                                                                   'investorCategoryDistinctions': '',
                                                                   'lotSize': '',
                                                                   'minimumApplicationAmount': '',
                                                                   'minimumApplicationLots': '',
                                                                   'professionalConfirmation': ''},
                                         'pricing': {'basisForIssuePriceReadiness': '',
                                                     'boardPricingCommitteeApproval': '',
                                                     'capPrice': '',
                                                     'finalIssuePrice': '',
                                                     'fixedIssuePrice': '',
                                                     'floorPrice': '',
                                                     'priceBand': '',
                                                     'priceBandApprovalDate': '',
                                                     'priceDiscoveryPending': '',
                                                     'pricingDate': '',
                                                     'pricingMethod': '',
                                                     'professionalConfirmation': ''}},
 'issueProgrammeAllotmentListingAndPostIssueExecution': {'allotmentSummaries': [],
                                                         'basisOfAllotment': {'allotmentDate': '',
                                                                              'allotmentFinalized': '',
                                                                              'approvalDateTime': '',
                                                                              'approvalReference': '',
                                                                              'basisDate': '',
                                                                              'basisPrepared': '',
                                                                              'boardCommitteeApproval': '',
                                                                              'exchangeApprovalReceived': '',
                                                                              'registrarReconciliationComplete': '',
                                                                              'technicalRejectionsFinalized': ''},
                                                         'dematCredit': {'cdslConfirmation': '',
                                                                         'completionDate': '',
                                                                         'completionTime': '',
                                                                         'corporateActionSubmitted': '',
                                                                         'exceptions': '',
                                                                         'nsdlConfirmation': '',
                                                                         'sharesCredited': ''},
                                                         'fundsUnblocking': {'debitInstructionsIssued': '',
                                                                             'delayedUnblockCases': '',
                                                                             'exceptions': '',
                                                                             'fundsReceived': '',
                                                                             'investorGrievances': '',
                                                                             'nonAllotteeUnblockComplete': '',
                                                                             'notes': '',
                                                                             'partialAllotteeUnblockComplete': '',
                                                                             'publicIssueAccountCredited': '',
                                                                             'scsbInstructionsStatus': '',
                                                                             'sponsorBankInstructionsIssued': ''},
                                                         'issueCalendar': {'anchorDate': '',
                                                                           'basisApprovalTarget': '',
                                                                           'basisOfAllotmentTarget': '',
                                                                           'bidRevisionDeadline': '',
                                                                           'fundTransferTarget': '',
                                                                           'issueClosingDate': '',
                                                                           'issueOpeningDate': '',
                                                                           'listingApplicationTarget': '',
                                                                           'listingTradingDate': '',
                                                                           'preIssueAdvertisementDate': '',
                                                                           'priceBandFixedPriceAnnouncementDate': '',
                                                                           'shareCreditTarget': '',
                                                                           'tradingApprovalTarget': '',
                                                                           'unblockTarget': '',
                                                                           'upiMandateDeadline': ''},
                                                         'issueOpeningReadiness': {'advertisementsReady': '',
                                                                                   'applicationFormsReady': '',
                                                                                   'bankingInfrastructureReady': '',
                                                                                   'certificatesCurrent': '',
                                                                                   'consentsCurrent': '',
                                                                                   'exchangePlatformReady': '',
                                                                                   'marketMakerReady': '',
                                                                                   'materialDevelopmentsUpdated': '',
                                                                                   'pricingFinalized': '',
                                                                                   'professionalGoLiveConfirmation': '',
                                                                                   'registrarReady': '',
                                                                                   'rhpProspectusRocFilingReady': '',
                                                                                   'sponsorBankReady': '',
                                                                                   'underwritingReady': ''},
                                                         'listing': {'applicationDateTime': '',
                                                                     'exchangeQueries': '',
                                                                     'finalListingApplicationSubmitted': '',
                                                                     'finalListingChecklistComplete': '',
                                                                     'listingCompletionStatus': '',
                                                                     'listingDate': '',
                                                                     'marketMakingCommenced': '',
                                                                     'tradingApprovalReceived': '',
                                                                     'tradingCommencement': '',
                                                                     'tradingNoticeReference': ''},
                                                         'postIssueActions': [],
                                                         'subscriptionRows': []},
 'issueTeamAndIntermediaryMaster': {'interSeAgreement': {'agreementDate': '',
                                                         'coordinatingLeadManagerIntermediaryId': '',
                                                         'identifiedOverlaps': '',
                                                         'identifiedResponsibilityGaps': '',
                                                         'interSeAgreementExecuted': '',
                                                         'interSeAgreementRequired': '',
                                                         'professionalReview': ''},
                                    'interSeResponsibilities': [],
                                    'intermediaries': [],
                                    'issueTeamSnapshot': {'allRequiredEngagementAgreementsExecuted': '',
                                                          'applicableRegistrationsReviewed': '',
                                                          'bankersToIssueAppointed': '',
                                                          'leadManagerAppointed': '',
                                                          'legalCounselAppointed': '',
                                                          'marketMakerAppointed': '',
                                                          'monitoringAgencyApplicable': '',
                                                          'monitoringAgencyAppointed': '',
                                                          'registrarAppointed': '',
                                                          'sponsorBankAppointed': '',
                                                          'statutoryPeerReviewAuditorEngaged': '',
                                                          'syndicateMembersApplicable': '',
                                                          'syndicateMembersAppointed': '',
                                                          'teamAsOfDate': '',
                                                          'underwritersAppointed': ''}},
 'schemaVersion': SCHEMA_VERSION,
 'underwritingMarketMakingAndDistributionArrangements': {'marketMakerConfiguration': {'agreementDate': '',
                                                                                      'agreementExecuted': '',
                                                                                      'exchange': '',
                                                                                      'mandatoryPeriod': '',
                                                                                      'marketMakerIntermediaryId': '',
                                                                                      'marketMakingCommencementDate': '',
                                                                                      'notes': '',
                                                                                      'operationalResponsibilitiesReviewed': '',
                                                                                      'professionalConfirmation': '',
                                                                                      'proposedEndDate': '',
                                                                                      'registrationReference': ''},
                                                         'marketMakerReservation': {'allocationStatus': '',
                                                                                    'discrepancyWithIpoSetup': '',
                                                                                    'inventoryReadiness': '',
                                                                                    'issuePrice': '',
                                                                                    'percentage': '',
                                                                                    'professionalConfirmation': '',
                                                                                    'reservationAmount': '',
                                                                                    'reservedShares': '',
                                                                                    'subscriptionResponsibility': ''},
                                                         'marketMakingArrangement': {'agreementDisclosed': '',
                                                                                     'backupContact': '',
                                                                                     'continuityProcess': '',
                                                                                     'exchangeApprovalStatus': '',
                                                                                     'fundingReadiness': '',
                                                                                     'inventorySource': '',
                                                                                     'nominatedInvestorArrangement': '',
                                                                                     'notes': '',
                                                                                     'operationalContact': '',
                                                                                     'promoterShareRestrictionsReviewed': '',
                                                                                     'quoteObligationsReviewed': '',
                                                                                     'settlementArrangement': ''},
                                                         'nominatedInvestors': [],
                                                         'underwritingCommitments': [],
                                                         'underwritingSummary': {'fullCoverageState': '',
                                                                                 'issueAmount': '',
                                                                                 'issueShares': '',
                                                                                 'leadManagerOwnAccountCommitment': '',
                                                                                 'ownAccountPercentage': '',
                                                                                 'professionalConfirmation': '',
                                                                                 'resourceSufficiencyReview': '',
                                                                                 'totalUnderwritingCommitment': '',
                                                                                 'totalUnderwritingPercentage': '',
                                                                                 'underwritingAgreementDate': '',
                                                                                 'underwritingAgreementExecuted': ''}}}


def empty_payload() -> dict[str, Any]:
    return deepcopy(_EMPTY_PAYLOAD)


def clone_empty_payload() -> dict[str, Any]:
    return deepcopy(_EMPTY_PAYLOAD)


def create_empty_intermediary_record(intermediary_id: str | None = None) -> dict[str, Any]:
    return {
        "intermediaryId": _new_id(intermediary_id),
        "legalName": "",
        "displayName": "",
        "roles": [],
        "contact": {
            "registeredOffice": "",
            "relevantCorporateBranchOffice": "",
            "telephone": "",
            "email": "",
            "investorGrievanceEmail": "",
            "website": "",
            "contactPerson": "",
            "designation": "",
            "cin": "",
        },
        "registration": {
            "registrationRequired": "",
            "sebiRegistrationNumber": "",
            "registrationCategory": "",
            "registrationStatus": "",
            "registrationExpiry": "",
            "exchangeMembership": "",
            "exchange": "",
            "marketMakerRegistrationReference": "",
            "otherRelevantRegistrationReference": "",
        },
        "appointment": {
            "appointmentDate": "",
            "boardApprovalReference": "",
            "engagementLetterDate": "",
            "agreementDate": "",
            "effectiveDate": "",
            "scope": "",
            "feeStructureSummary": "",
            "reimbursementArrangement": "",
            "status": "",
            "replacementIntermediaryId": "",
            "replacementReason": "",
            "professionalConfirmation": "",
            "notes": "",
        },
    }


def create_empty_filing_record(filing_id: str | None = None) -> dict[str, Any]:
    return {
        "filingId": _new_id(filing_id),
        "linkedDocumentVersionId": "",
        "documentType": "",
        "documentDate": "",
        "internalVersion": "",
        "filingStage": "",
        "status": "",
        "authority": "",
        "selectedAuthorityExchange": "",
        "filingDate": "",
        "filingTime": "",
        "referenceApplicationNumber": "",
        "acknowledgementReceived": "",
        "acknowledgementDate": "",
        "submittedBy": "",
        "responsibleLeadManagerIntermediaryId": "",
        "supersededByFilingId": "",
        "notes": "",
    }


def create_empty_offer_document_version_record(document_version_id: str | None = None) -> dict[str, Any]:
    return {
        "documentVersionId": _new_id(document_version_id),
        "type": "",
        "date": "",
        "versionLabel": "",
        "filingStage": "",
        "filedAuthority": "",
        "boardApproved": "",
        "signed": "",
        "supersedesDocumentVersionId": "",
        "currentAuthoritativeVersion": "",
        "pageCount": "",
        "openPlaceholderCount": "",
        "openCommentCount": "",
        "chapterSignOffCompletionStatus": "",
        "professionalConfirmation": "",
        "notes": "",
    }
