import {
  createEmptyBusinessOperationsPayload,
  createEmptyBusinessUnit,
  createEmptyCompetitiveStrength,
  createEmptyCustomerConcentrationPeriod,
  createEmptyFacility,
  createEmptyGeographicRevenue,
  createEmptyIntellectualPropertyRecord,
  createEmptyKeyDependency,
  createEmptyKeyInput,
  createEmptyMachineryEquipment,
  createEmptyMaterialCustomer,
  createEmptyMaterialSupplier,
  createEmptyProductService,
  createEmptyQualityCertification,
  createEmptyRevenueMixRow,
  createEmptySalesChannel,
  createEmptyStrategyItem,
  createEmptySupplierConcentrationPeriod,
  createEmptyWorkforcePeriod,
} from '@/lib/business-operations/defaults';
import type { BusinessOperationsPayload } from '@/lib/schemas/business-operations';
import { NIVARA_BUSINESS, NIVARA_FINANCIAL_PERIODS, NIVARA_ISSUER } from './constants';

const PRODUCT_MACHINED_ID = 'nivara-product-machined-components';
const PRODUCT_ASSEMBLY_ID = 'nivara-product-electromechanical-assemblies';
const PRODUCT_JOBWORK_ID = 'nivara-product-tooling-jobwork';

export function createNivaraBusinessOperationsPayload(): BusinessOperationsPayload {
  const payload = createEmptyBusinessOperationsPayload();

  payload.businessProfileAndOperatingModel = {
    ...payload.businessProfileAndOperatingModel,
    businessCommencementDate: '2019-08-01',
    businessClassifications: ['manufacturing'],
    primaryBusinessActivity: NIVARA_BUSINESS.primaryIndustry,
    briefBusinessOverview:
      'Nivara Techfab manufactures precision metal components and electromechanical assemblies for automotive and industrial OEM customers from its Pune facility.',
    positionInValueChain: 'tier-2-supplier',
    customerModel: 'b2b',
    revenueModels: ['product-sales', 'job-work'],
    orderModel: 'purchase-orders',
    domesticOperations: 'yes',
    exportOperations: 'no',
    regionsCountriesServed: 'Maharashtra, Gujarat, Tamil Nadu',
    seasonalityOrCyclicality: 'no',
    workingCapitalIntensiveBusiness: 'yes',
    materialThirdPartyDependence: 'no',
    materialRegulatoryDependence: 'no',
    valueCreationAndDeliveryExplanation:
      'Nivara sources alloy steel and sub-components, machines precision parts on CNC lines, assembles electromechanical sub-assemblies, and delivers against OEM purchase orders with in-process quality checks.',
    businessUnits: [
      {
        ...createEmptyBusinessUnit('nivara-bu-manufacturing'),
        unitName: 'Bhosari manufacturing division',
        status: 'active',
        activity: 'CNC machining and electromechanical assembly',
        commencementDate: '2019-08-01',
        geography: `${NIVARA_ISSUER.registeredOfficeCity}, Maharashtra`,
        revenueContributionPercentage: '100',
      },
    ],
  };

  payload.productsServicesAndRevenueMix = {
    ...payload.productsServicesAndRevenueMix,
    productsServices: [
      {
        ...createEmptyProductService(PRODUCT_MACHINED_ID),
        name: 'Precision machined components',
        productType: 'product',
        businessSegment: 'Manufacturing',
        description: 'CNC-turned and milled components for automotive transmission and braking systems.',
        customerOrEndUserType: 'Automotive Tier-1 suppliers',
        industryServed: 'Automotive',
        lifecycleStage: 'growth',
        sourcingModel: 'in-house',
        pricingModel: 'Per-unit contract pricing',
        domesticExportClassification: 'domestic',
      },
      {
        ...createEmptyProductService(PRODUCT_ASSEMBLY_ID),
        name: 'Electromechanical assemblies',
        productType: 'product',
        businessSegment: 'Manufacturing',
        description: 'Sub-assemblies integrating metal parts, fasteners and electromechanical sub-components.',
        customerOrEndUserType: 'Industrial OEM customers',
        industryServed: 'Industrial equipment',
        lifecycleStage: 'growth',
        sourcingModel: 'mixed',
        pricingModel: 'Bill of materials plus conversion charge',
        domesticExportClassification: 'domestic',
      },
      {
        ...createEmptyProductService(PRODUCT_JOBWORK_ID),
        name: 'Tooling and job-work services',
        productType: 'service',
        businessSegment: 'Job-work',
        description: 'Short-run tooling, prototyping and contract manufacturing for existing customers.',
        customerOrEndUserType: 'Existing OEM accounts',
        industryServed: 'Automotive and industrial',
        lifecycleStage: 'maturity',
        sourcingModel: 'in-house',
        pricingModel: 'Time and material / lot basis',
        domesticExportClassification: 'domestic',
      },
    ],
    revenueMixRows: [
      {
        ...createEmptyRevenueMixRow('nivara-revenue-fy2022-machined'),
        productOrSegmentId: PRODUCT_MACHINED_ID,
        productOrSegmentLabel: 'Precision machined components',
        financialYear: 'FY 2022',
        revenue: '2310',
        percentageOfRevenueFromOperations: '55',
        source: 'audited-financials',
      },
      {
        ...createEmptyRevenueMixRow('nivara-revenue-fy2022-assembly'),
        productOrSegmentId: PRODUCT_ASSEMBLY_ID,
        productOrSegmentLabel: 'Electromechanical assemblies',
        financialYear: 'FY 2022',
        revenue: '1260',
        percentageOfRevenueFromOperations: '30',
        source: 'audited-financials',
      },
      {
        ...createEmptyRevenueMixRow('nivara-revenue-fy2022-jobwork'),
        productOrSegmentId: PRODUCT_JOBWORK_ID,
        productOrSegmentLabel: 'Tooling and job-work services',
        financialYear: 'FY 2022',
        revenue: '630',
        percentageOfRevenueFromOperations: '15',
        source: 'audited-financials',
      },
      {
        ...createEmptyRevenueMixRow('nivara-revenue-fy2023-machined'),
        productOrSegmentId: PRODUCT_MACHINED_ID,
        productOrSegmentLabel: 'Precision machined components',
        financialYear: 'FY 2023',
        revenue: '2805',
        percentageOfRevenueFromOperations: '55',
        source: 'audited-financials',
      },
      {
        ...createEmptyRevenueMixRow('nivara-revenue-fy2023-assembly'),
        productOrSegmentId: PRODUCT_ASSEMBLY_ID,
        productOrSegmentLabel: 'Electromechanical assemblies',
        financialYear: 'FY 2023',
        revenue: '1530',
        percentageOfRevenueFromOperations: '30',
        source: 'audited-financials',
      },
      {
        ...createEmptyRevenueMixRow('nivara-revenue-fy2023-jobwork'),
        productOrSegmentId: PRODUCT_JOBWORK_ID,
        productOrSegmentLabel: 'Tooling and job-work services',
        financialYear: 'FY 2023',
        revenue: '765',
        percentageOfRevenueFromOperations: '15',
        source: 'audited-financials',
      },
      {
        ...createEmptyRevenueMixRow('nivara-revenue-fy2024-machined'),
        productOrSegmentId: PRODUCT_MACHINED_ID,
        productOrSegmentLabel: 'Precision machined components',
        financialYear: 'FY 2024',
        revenue: '3465',
        percentageOfRevenueFromOperations: '55',
        source: 'audited-financials',
      },
      {
        ...createEmptyRevenueMixRow('nivara-revenue-fy2024-assembly'),
        productOrSegmentId: PRODUCT_ASSEMBLY_ID,
        productOrSegmentLabel: 'Electromechanical assemblies',
        financialYear: 'FY 2024',
        revenue: '1890',
        percentageOfRevenueFromOperations: '30',
        source: 'audited-financials',
      },
      {
        ...createEmptyRevenueMixRow('nivara-revenue-fy2024-jobwork'),
        productOrSegmentId: PRODUCT_JOBWORK_ID,
        productOrSegmentLabel: 'Tooling and job-work services',
        financialYear: 'FY 2024',
        revenue: '945',
        percentageOfRevenueFromOperations: '15',
        source: 'audited-financials',
      },
    ],
  };

  payload.customersSalesDistributionAndGeography = {
    ...payload.customersSalesDistributionAndGeography,
    approximateActiveCustomerCount: '18',
    customerCategories: 'Automotive Tier-1 suppliers and industrial OEM customers',
    industriesServed: 'Automotive, industrial machinery, electrical equipment',
    repeatCustomerPercentage: '82',
    governmentTenderDependence: 'no',
    largeEnterpriseDependence: 'yes',
    longTermContractsAvailable: 'yes',
    purchaseOrderDependence: 'yes',
    customerConcentrationPeriods: [
      {
        ...createEmptyCustomerConcentrationPeriod('nivara-customer-conc-fy2024'),
        periodLabel: 'FY 2024',
        isCurrentPeriod: true,
        largestCustomerPercentage: '28',
        top3Percentage: '58',
        totalRevenueFromOperations: '6300',
        source: 'management-records',
      },
    ],
    materialCustomers: [
      {
        ...createEmptyMaterialCustomer('nivara-customer-001'),
        customerNameOrConfidentialLabel: 'Automotive Tier-1 account (confidential)',
        industry: 'Automotive',
        country: 'India',
        relationshipSince: '2020-04-01',
        revenueContributionPercentage: '28',
        contractType: 'Annual supply agreement with rolling POs',
      },
      {
        ...createEmptyMaterialCustomer('nivara-customer-002'),
        customerNameOrConfidentialLabel: 'Industrial OEM account (confidential)',
        industry: 'Industrial equipment',
        country: 'India',
        relationshipSince: '2021-01-15',
        revenueContributionPercentage: '18',
        contractType: 'Framework agreement',
      },
    ],
    salesChannels: [
      {
        ...createEmptySalesChannel('nivara-channel-direct'),
        channelType: 'direct-sales',
        geography: 'India — Western and Southern regions',
        revenueContributionPercentage: '100',
        keyDependency: 'yes',
      },
    ],
    geographicRevenueRows: [
      {
        ...createEmptyGeographicRevenue('nivara-geo-fy2024-india'),
        periodLabel: 'FY 2024',
        geographicScope: 'india',
        regionOrCountry: 'India',
        revenue: '6300',
        percentageOfRevenue: '100',
        source: 'audited-financials',
      },
    ],
    orderBookAvailable: 'no',
  };

  payload.suppliersProcurementInventoryAndLogistics = {
    ...payload.suppliersProcurementInventoryAndLogistics,
    keyInputs: [
      {
        ...createEmptyKeyInput('nivara-input-alloy-steel'),
        inputName: 'Alloy steel bars and billets',
        category: 'raw-material',
        productsServicesSupported: 'Precision machined components',
        domesticOrImported: 'domestic',
        criticalInput: 'yes',
        substituteAvailable: 'yes',
        typicalLeadTime: '2–3 weeks',
      },
      {
        ...createEmptyKeyInput('nivara-input-fasteners'),
        inputName: 'Industrial fasteners and electromechanical sub-components',
        category: 'component',
        productsServicesSupported: 'Electromechanical assemblies',
        domesticOrImported: 'domestic',
        criticalInput: 'yes',
        substituteAvailable: 'yes',
        typicalLeadTime: '1–2 weeks',
      },
    ],
    supplierConcentrationPeriods: [
      {
        ...createEmptySupplierConcentrationPeriod('nivara-supplier-conc-fy2024'),
        periodLabel: 'FY 2024',
        isCurrentPeriod: true,
        totalSuppliers: '42',
        largestSupplierPercentage: '22',
        top3Percentage: '48',
        totalPurchases: '3850',
        importedPurchasePercentage: '5',
        source: 'management-records',
      },
    ],
    materialSuppliers: [
      {
        ...createEmptyMaterialSupplier('nivara-supplier-001'),
        supplierNameOrConfidentialLabel: 'Steel distributor (confidential)',
        inputSupplied: 'Alloy steel bars and billets',
        relationshipSince: '2019-09-01',
        country: 'India',
        longTermAgreement: 'yes',
        singleSourceDependency: 'no',
      },
      {
        ...createEmptyMaterialSupplier('nivara-supplier-002'),
        supplierNameOrConfidentialLabel: 'Component vendor (confidential)',
        inputSupplied: 'Fasteners and electromechanical sub-components',
        relationshipSince: '2020-06-01',
        country: 'India',
        longTermAgreement: 'no',
        singleSourceDependency: 'no',
      },
    ],
    procurementModel: 'centralised',
    relatedPartySupplierDependence: 'no',
    productionModel: 'make-to-order',
    materialWriteOffs: 'no',
    logisticsModel: 'third-party',
    warehousingArrangement: 'Leased warehouse bay within Bhosari industrial estate',
    transportModes: 'Road freight',
    deliveryResponsibilities: 'Ex-works Bhosari; customer-arranged freight for most accounts',
  };

  payload.facilitiesCapacityAndOperationalProcess = {
    ...payload.facilitiesCapacityAndOperationalProcess,
    facilities: [
      {
        ...createEmptyFacility('nivara-bo-primary-facility'),
        name: 'Bhosari manufacturing unit',
        facilityType: 'manufacturing-plant',
        address: NIVARA_BUSINESS.primaryFacility,
        stateOrCountry: 'Maharashtra, India',
        tenure: 'leased',
        operationalSince: '2019-08-01',
        status: 'operational',
        area: '45000 sq. ft.',
        mainFunctions: 'CNC machining, assembly, quality inspection',
        productsServicesSupported: 'Precision components and electromechanical assemblies',
        numberOfShifts: '2',
        workforceCount: '85',
        leaseExpiry: '2029-03-31',
      },
    ],
    electricityDependency: 'yes',
    waterDependency: 'yes',
    wasteManagementArrangements: 'Scrap metal sold to authorised recyclers; coolant treated on-site',
  };

  payload.technologyQualityResearchAndIntellectualProperty = {
    ...payload.technologyQualityResearchAndIntellectualProperty,
    coreOperatingTechnology:
      'CNC turning and milling, precision grinding, and electromechanical assembly with in-process SPC on critical dimensions',
    technologyOwnership: 'mixed',
    automationLevel: 'semi-automated',
    criticalSoftwareSystems: 'CNC program storage, production scheduling, and quality data capture',
    thirdPartyTechnologyDependence: 'no',
    machineryAndEquipment: [
      {
        ...createEmptyMachineryEquipment('nivara-cnc-line'),
        nameOrType: 'CNC turning and milling centres',
        facilityId: 'nivara-bo-primary-facility',
        facilityName: 'Bhosari manufacturing unit',
        functionDescription: 'Precision machining of automotive and industrial components',
        quantity: '14',
        ageYears: '4',
        status: 'operational',
      },
    ],
    qualityProcess:
      'Incoming material inspection, in-process checks with SPC on critical dimensions, and final dimensional/visual inspection before dispatch',
    inspectionStages: 'Incoming, in-process, pre-dispatch',
    qualityClaims: 'no',
    materialRecallDeclaration: 'no',
    certifications: [
      {
        ...createEmptyQualityCertification('nivara-iso-9001'),
        standard: 'ISO 9001:2015',
        issuingBody: 'Accredited certification body',
        scope: 'Manufacture of precision metal components and assemblies',
        issueDate: '2021-03-15',
        expiryDate: '2027-03-14',
        renewalStatus: 'current',
      },
    ],
    rdFunctionExists: 'yes',
    rdDeliveryModel: 'internal',
    rdEmployeeCount: '8',
    rdCurrentProjects: 'Tooling optimisation and cycle-time reduction for transmission components',
    intellectualPropertyRecords: [
      {
        ...createEmptyIntellectualPropertyRecord('nivara-ip-trademark'),
        ipType: 'trademark',
        nameOrDescription: `${NIVARA_ISSUER.shortName} word mark`,
        ownerOrApplicant: NIVARA_ISSUER.legalName,
        jurisdiction: 'India',
        status: 'registered',
        registrationDate: '2020-11-20',
        ownershipModel: 'owned',
        materialityStatus: 'not-material',
      },
    ],
  };

  payload.workforceCollaborationsInsuranceAndContinuity = {
    ...payload.workforceCollaborationsInsuranceAndContinuity,
    workforcePeriods: [
      {
        ...createEmptyWorkforcePeriod('nivara-workforce-fy2024'),
        asOfDate: NIVARA_FINANCIAL_PERIODS.fy2024End,
        periodLabel: 'FY 2024',
        isCurrentPeriod: true,
        permanentEmployees: '78',
        contractWorkers: '7',
        factoryOrOperationalWorkers: '62',
        technicalOrRdEmployees: '8',
        salesEmployees: '6',
        administrationEmployees: '9',
        womenEmployees: '14',
        attritionPercentage: '11',
        geographicDistribution: `${NIVARA_ISSUER.registeredOfficeCity}, Maharashtra`,
      },
    ],
    labourDisputes: 'no',
    specialisedSkillDependence: 'yes',
    specialisedSkillDependenceDetails:
      'CNC programmers, tool-room technicians, and quality inspectors with automotive tolerance experience',
    labourContractorUsage: 'yes',
    managementConsidersCoverageAdequate: 'yes',
    businessContinuityPlanExists: 'yes',
    disasterRecoveryPlanExists: 'yes',
  };

  payload.competitiveStrengthsStrategyDependenciesAndConfirmations = {
    ...payload.competitiveStrengthsStrategyDependenciesAndConfirmations,
    competitiveStrengths: [
      {
        ...createEmptyCompetitiveStrength('nivara-strength-precision'),
        title: 'Precision machining capability for automotive OEM tolerances',
        explanation:
          'In-house CNC lines and SPC-backed quality processes support repeat supply to tier-1 automotive accounts.',
        supportingMetric: 'Average rejection rate below 1.2% on critical lots in FY 2024',
        period: 'FY 2024',
        supportingSource: 'Internal quality records and customer audit feedback',
        relatedProductFacilityOrCustomer: 'Precision machined components — Bhosari unit',
      },
      {
        ...createEmptyCompetitiveStrength('nivara-strength-lead-times'),
        title: 'Responsive make-to-order lead times for existing OEM accounts',
        explanation:
          'Centralised procurement and two-shift operations enable short-run replenishment against rolling purchase orders.',
        supportingMetric: 'Typical repeat-order lead time of 10–14 days for standard lots',
        period: 'FY 2024',
        supportingSource: 'Production planning records',
      },
    ],
    strategies: [
      {
        ...createEmptyStrategyItem('nivara-strategy-capacity'),
        title: 'Phase II capacity expansion at Bhosari facility',
        description:
          'Add CNC capacity and assembly bays to support growth from existing automotive OEM customers; partially funded through IPO proceeds.',
        category: 'capacity-expansion',
        timeHorizon: 'medium-term',
        currentStatus: 'in-progress',
        relatedObjectsOfTheIssueReference: 'Capex for additional machining and assembly lines',
        containsUnsupportedProjections: 'no',
      },
    ],
    keyDependencies: [
      {
        ...createEmptyKeyDependency('nivara-dep-customers'),
        dependencyType: 'customer',
        description:
          'Continued purchase orders from top automotive tier-1 and industrial OEM accounts representing majority of revenue',
        materialityStatus: 'material',
        mitigation: 'Diversified across 18 active accounts; no single customer above 30% of revenue',
      },
      {
        ...createEmptyKeyDependency('nivara-dep-suppliers'),
        dependencyType: 'supplier',
        description: 'Timely availability of alloy steel and approved component vendors',
        materialityStatus: 'material',
        mitigation: 'Dual sourcing for critical inputs; safety stock on high-turnover grades',
      },
    ],
    confirmations: {
      allMaterialActivitiesDisclosed: true,
      productsAndServicesAreComplete: true,
      revenueMixReconciles: true,
      customerConcentrationIsComplete: true,
      supplierConcentrationIsComplete: true,
      allFacilitiesAreIncluded: true,
      capacityUnitsAndFiguresAreConsistent: true,
      outsourcedOperationsAreDisclosed: true,
      technologyAndIpDependenciesAreDisclosed: true,
      qualityIncidentsAndRecallsAreDisclosed: true,
      insuranceAndContinuityInformationIsComplete: true,
      strengthClaimsHaveSupportingSources: true,
      strategiesContainNoUnsupportedProjections: true,
      professionalReviewRemainsRequired: true,
    },
  };

  return payload;
}
