import {
  createEmptyBeneficialOwner,
  createEmptyCapitalEvent,
  createEmptyCapitalOwnershipPayload,
  createEmptyEquityShareClass,
  createEmptyPromoter,
  createEmptyPromoterContributionLot,
  createEmptyShareholder,
  createEmptyShareholderOfferOverlay,
} from '@/lib/capital-ownership/defaults';
import type { CapitalOwnershipPayload } from '@/lib/schemas/capital-ownership';
import {
  NIVARA_CAPITAL,
  NIVARA_FINANCIAL_PERIODS,
  NIVARA_IDS,
  NIVARA_ISSUER,
  NIVARA_PEOPLE,
} from './constants';

export function createNivaraCapitalOwnershipPayload(): CapitalOwnershipPayload {
  const payload = createEmptyCapitalOwnershipPayload();

  payload.currentCapitalStructure = {
    ...payload.currentCapitalStructure,
    asOnDate: NIVARA_FINANCIAL_PERIODS.fy2024End,
    equityClasses: [
      {
        ...createEmptyEquityShareClass(NIVARA_CAPITAL.equityClassId),
        className: 'Equity Shares of ₹10 each',
        classType: 'ordinary-equity',
        faceValuePerShare: NIVARA_CAPITAL.faceValuePerShare,
        votingRightsPerShare: '1',
        authorisedShares: NIVARA_CAPITAL.authorisedEquityShares,
        issuedShares: NIVARA_CAPITAL.preIssueEquityShares,
        subscribedShares: NIVARA_CAPITAL.preIssueEquityShares,
        paidUpShares: NIVARA_CAPITAL.preIssueEquityShares,
        dematStatus: 'partly-dematerialised',
      },
    ],
    hasPreferenceShares: 'no',
    authorisedEquityShareCapital: '80000000',
    issuedEquityShareCapital: NIVARA_CAPITAL.paidUpEquityCapital,
    subscribedEquityShareCapital: NIVARA_CAPITAL.paidUpEquityCapital,
    paidUpEquityShareCapital: NIVARA_CAPITAL.paidUpEquityCapital,
    paidUpCapitalAsPerLatestAuditedFinancials: NIVARA_CAPITAL.paidUpEquityCapital,
    latestAuditedFinancialYearEnd: NIVARA_FINANCIAL_PERIODS.fy2024End,
    shareCapitalMatchesMcaRecords: 'yes',
    allSharesFullyPaidUp: 'yes',
    authorisedCapitalSufficientForProposedIssue: 'yes',
    dematStatusOverall: 'partly-dematerialised',
  };

  payload.shareCapitalHistory = {
    ...payload.shareCapitalHistory,
    historyCoversPeriodSinceIncorporation: 'yes',
    historyStartDate: NIVARA_ISSUER.incorporationDate,
    capitalEvents: [
      {
        ...createEmptyCapitalEvent('nivara-capital-event-incorporation'),
        eventDate: NIVARA_ISSUER.incorporationDate,
        eventType: 'incorporation-initial-subscription',
        securityType: 'equity',
        description: 'Initial subscription on incorporation',
        numberOfShares: '4500000',
        faceValuePerShare: NIVARA_CAPITAL.faceValuePerShare,
        issuePricePerShare: NIVARA_CAPITAL.faceValuePerShare,
        totalConsiderationAmount: NIVARA_CAPITAL.paidUpEquityCapital,
        considerationType: 'cash',
        includesPromoterAllotment: 'yes',
        resolutionType: 'not-applicable',
        rocFilingCompleted: 'yes',
      },
    ],
    allHistoricalAllotmentsDocumented: 'yes',
    historyReconciledWithMcaFilings: 'yes',
    bonusIssueInLastTwelveMonths: 'no',
    sharesIssuedForConsiderationOtherThanCashInLastTwelveMonths: 'no',
    anyPendingAllotments: 'no',
  };

  payload.shareholdersAndBeneficialOwnership = {
    ...payload.shareholdersAndBeneficialOwnership,
    shareholdingAsOnDate: NIVARA_FINANCIAL_PERIODS.fy2024End,
    shareholders: [
      {
        ...createEmptyShareholder(NIVARA_IDS.shareholder001),
        name: NIVARA_PEOPLE.promoter1.name,
        holderType: 'individual',
        category: 'promoter',
        residentialStatus: 'resident',
        nationality: 'Indian',
        identifierType: 'pan',
        directorIdentificationNumber: NIVARA_PEOPLE.promoter1.din,
        equityClassId: NIVARA_CAPITAL.equityClassId,
        equitySharesHeld: '2700000',
        sharesInDematerialisedForm: '2700000',
        dateOfEarliestAcquisition: '2019-06-12',
        modeOfAcquisition: 'subscription-to-memorandum',
        isPartOfPromoterGroup: 'no',
        beneficialOwnerIsDifferent: 'no',
        isSellingShareholderInOffer: 'no',
      },
      {
        ...createEmptyShareholder(NIVARA_IDS.shareholder002),
        name: NIVARA_PEOPLE.promoter2.name,
        holderType: 'individual',
        category: 'promoter',
        residentialStatus: 'resident',
        nationality: 'Indian',
        identifierType: 'pan',
        directorIdentificationNumber: NIVARA_PEOPLE.promoter2.din,
        equityClassId: NIVARA_CAPITAL.equityClassId,
        equitySharesHeld: '1800000',
        sharesInDematerialisedForm: '1800000',
        dateOfEarliestAcquisition: '2019-06-12',
        modeOfAcquisition: 'subscription-to-memorandum',
        isPartOfPromoterGroup: 'no',
        beneficialOwnerIsDifferent: 'no',
        isSellingShareholderInOffer: 'no',
      },
    ],
    totalNumberOfShareholders: '2',
    registerOfMembersMaintained: 'yes',
    registerOfMembersUpToDate: 'yes',
    shareholdingReconciledWithRegisterOfMembers: 'yes',
    significantBeneficialOwnerDeterminationCompleted: 'yes',
    foreignShareholdingExists: 'no',
    anyShareholderAgreementsWithInvestors: 'no',
    beneficialOwners: [
      {
        ...createEmptyBeneficialOwner('nivara-beneficial-owner-001'),
        name: NIVARA_PEOPLE.promoter1.name,
        linkedShareholderId: NIVARA_IDS.shareholder001,
        identifierType: 'pan',
        identifierValue: 'ABCPM1234A',
        nationality: 'Indian',
        residentialStatus: 'resident',
        isSignificantBeneficialOwner: 'yes',
        natureOfInterest: 'shares',
        directHoldingPercentage: '60',
        indirectHoldingPercentage: '0',
        dateOfBecomingBeneficialOwner: '2019-06-12',
        declarationInFormBen1Received: 'yes',
        formBen2Filed: 'yes',
        registerInFormBen3Maintained: 'yes',
      },
    ],
  };

  payload.promotersAndControl = {
    ...payload.promotersAndControl,
    companyHasIdentifiedPromoter: 'yes',
    promoters: [
      {
        ...createEmptyPromoter(NIVARA_IDS.promoter001),
        name: NIVARA_PEOPLE.promoter1.name,
        promoterType: 'individual',
        linkedShareholderId: NIVARA_IDS.shareholder001,
        identifierType: 'pan',
        directorIdentificationNumber: NIVARA_PEOPLE.promoter1.din,
        nationality: 'Indian',
        residentialStatus: 'resident',
        dateOfBecomingPromoter: '2019-06-12',
        basisOfPromoterStatus: 'shareholding',
        equitySharesHeld: '2700000',
        isAlsoDirector: 'yes',
        designation: 'Managing Director',
        isPartOfPromoterSellingInOffer: 'no',
      },
      {
        ...createEmptyPromoter(NIVARA_IDS.promoter002),
        name: NIVARA_PEOPLE.promoter2.name,
        promoterType: 'individual',
        linkedShareholderId: NIVARA_IDS.shareholder002,
        identifierType: 'pan',
        directorIdentificationNumber: NIVARA_PEOPLE.promoter2.din,
        nationality: 'Indian',
        residentialStatus: 'resident',
        dateOfBecomingPromoter: '2019-06-12',
        basisOfPromoterStatus: 'shareholding',
        equitySharesHeld: '1800000',
        isAlsoDirector: 'yes',
        designation: 'Whole-time Director',
        isPartOfPromoterSellingInOffer: 'no',
      },
    ],
    promoterIdentificationComplete: 'yes',
    promoterGroupIdentificationComplete: 'yes',
    anyPromoterIsBodyCorporate: 'no',
    anyPromoterClassifiedAsWilfulDefaulter: 'no',
    anyPersonExercisingControlWithoutShareholding: 'no',
    changeInControlInLastThreeYears: 'no',
  };

  payload.preAndPostIssueOwnership = {
    ...payload.preAndPostIssueOwnership,
    shareholderOverlays: [
      {
        ...createEmptyShareholderOfferOverlay(NIVARA_IDS.shareholder001, 'nivara-overlay-001'),
        otherExpectedPreIssueTransfer: '0',
      },
      {
        ...createEmptyShareholderOfferOverlay(NIVARA_IDS.shareholder002, 'nivara-overlay-002'),
        otherExpectedPreIssueTransfer: '0',
      },
    ],
    freshIssueSharesOverride: NIVARA_CAPITAL.freshIssueShares,
    preIssueCapitalConfirmedWithLeadManager: 'yes',
    sellingShareholderConsentsObtained: 'no',
    anyExpectedPreIssueTransfers: 'no',
  };

  payload.promoterContributionLockInAndEncumbrances = {
    ...payload.promoterContributionLockInAndEncumbrances,
    minimumPromoterContributionApplicable: 'yes',
    targetMinimumContributionPercentage: '20',
    contributionLots: [
      {
        ...createEmptyPromoterContributionLot('nivara-contribution-lot-001'),
        promoterId: NIVARA_IDS.promoter001,
        shareholderId: NIVARA_IDS.shareholder001,
        holderName: NIVARA_PEOPLE.promoter1.name,
        numberOfShares: '2700000',
        faceValuePerShare: NIVARA_CAPITAL.faceValuePerShare,
        dateOfAcquisition: '2019-06-12',
        dateOfAllotmentOrTransfer: '2019-06-12',
        modeOfAcquisition: 'cash-subscription',
        fullyPaidUp: 'yes',
        dematerialised: 'yes',
        eligibleForMinimumPromoterContribution: 'yes',
        proposedLockInPeriod: 'three-years',
        isEncumbered: 'no',
      },
      {
        ...createEmptyPromoterContributionLot('nivara-contribution-lot-002'),
        promoterId: NIVARA_IDS.promoter002,
        shareholderId: NIVARA_IDS.shareholder002,
        holderName: NIVARA_PEOPLE.promoter2.name,
        numberOfShares: '1800000',
        faceValuePerShare: NIVARA_CAPITAL.faceValuePerShare,
        dateOfAcquisition: '2019-06-12',
        dateOfAllotmentOrTransfer: '2019-06-12',
        modeOfAcquisition: 'cash-subscription',
        fullyPaidUp: 'yes',
        dematerialised: 'yes',
        eligibleForMinimumPromoterContribution: 'yes',
        proposedLockInPeriod: 'three-years',
        isEncumbered: 'no',
      },
    ],
    contributionBroughtInBeforeIssueOpening: 'yes',
    anyEncumbranceOnPromoterShares: 'no',
    entirePreIssueCapitalLockInUnderstood: 'yes',
    sharesIneligibleForContributionExist: 'no',
  };

  payload.outstandingSecuritiesTransactionsAndConfirmations = {
    ...payload.outstandingSecuritiesTransactionsAndConfirmations,
    anyOutstandingConvertibleInstruments: 'no',
    anyTransactionsInLastEighteenMonths: 'no',
    allSharesDematerialisedBeforeFiling: 'no',
    anyPendingShareTransfers: 'no',
    anyDisputesOverTitleToShares: 'no',
    confirmations: {
      capitalStructureFiguresMatchStatutoryRegisters: true,
      shareCapitalHistoryIsComplete: true,
      shareholdingDetailsAreCurrentAsOnStatedDate: true,
      promoterAndPromoterGroupIdentificationIsComplete: true,
      allOutstandingConvertibleInstrumentsDisclosed: true,
      allEncumbrancesOnPromoterSharesDisclosed: true,
      noUndisclosedShareholderAgreementsOrControlArrangements: true,
      offerForSaleSharesAreWithinExistingHoldings: true,
      missingAnswersMustNotBeInterpretedAsNegative: true,
      computedFiguresAreIndicativeOnly: true,
      professionalAndRegistrarConfirmationRemainRequired: true,
    },
  };

  return payload;
}
