import type { CompanyIncorporationSessionData } from '@/lib/company-incorporation/defaults';
import {
  NIVARA_FINANCIAL_PERIODS,
  NIVARA_IDS,
  NIVARA_ISSUER,
  NIVARA_PEOPLE,
} from '@/lib/demo-data/nivara/constants';

export function createNivaraCompanyIncorporationPayload(): CompanyIncorporationSessionData {
  return {
    identity: {
      legalName: NIVARA_ISSUER.legalName,
      shortName: NIVARA_ISSUER.shortName,
      cin: NIVARA_ISSUER.cin,
      registrationNumber: '',
      incorporationDate: NIVARA_ISSUER.incorporationDate,
      incorporationCity: NIVARA_ISSUER.incorporationCity,
      incorporationState: NIVARA_ISSUER.incorporationState,
      registrarOfCompanies: NIVARA_ISSUER.registrarOfCompanies,
      companyClass: 'private',
      companyCategory: 'company-limited-by-shares',
      companySubCategory: 'non-government-company',
      specialCompanyType: 'none',
      companyStatus: 'active',
      listedStatus: 'unlisted',
      commencementDate: '2019-08-01',
      governingAct: 'companies-act-2013',
      website: NIVARA_ISSUER.website,
      email: NIVARA_ISSUER.email,
      telephone: NIVARA_ISSUER.telephone,
      issuerContactPersonId: '',
    },
    corporateEvents: [
      {
        id: NIVARA_IDS.corporateEvent001,
        eventType: 'original-incorporation',
        eventStatus: 'effective',
        effectiveDate: NIVARA_ISSUER.incorporationDate,
        previousValue: '',
        newValue: NIVARA_ISSUER.legalName,
        description: 'Incorporation as Nivara Techfab Private Limited',
        reason: 'Initial incorporation',
        boardResolutionDate: '',
        shareholderResolutionDate: '',
        approvalAuthority: 'Registrar of Companies, Pune',
        filingForm: 'INC-32',
        srn: 'AB1234567',
        filingDate: NIVARA_ISSUER.incorporationDate,
        certificateOrOrderDate: NIVARA_ISSUER.incorporationDate,
      },
    ],
    offices: [
      {
        id: NIVARA_IDS.office001,
        officeType: 'registered-office',
        addressLine1: NIVARA_ISSUER.registeredOfficeLine1,
        addressLine2: NIVARA_ISSUER.registeredOfficeLine2,
        locality: NIVARA_ISSUER.registeredOfficeLocality,
        city: NIVARA_ISSUER.registeredOfficeCity,
        district: NIVARA_ISSUER.registeredOfficeDistrict,
        state: NIVARA_ISSUER.registeredOfficeState,
        pinCode: NIVARA_ISSUER.registeredOfficePin,
        country: 'India',
        effectiveFrom: NIVARA_ISSUER.incorporationDate,
        effectiveUntil: '',
        occupancyType: 'leased',
      },
    ],
    constitutionalRecord: {
      moaVersionDate: NIVARA_FINANCIAL_PERIODS.fy2024End,
      aoaVersionDate: NIVARA_FINANCIAL_PERIODS.fy2024End,
      moaCertifiedCopyStatus: 'available',
      aoaCertifiedCopyStatus: 'available',
      mainObjectClauseNumbers: ['III(A)(1)'],
      mainObjectText:
        'To manufacture, fabricate, assemble and trade in precision metal components, electromechanical assemblies and related industrial products.',
      latestMoaAmendmentDate: '',
      latestAoaAmendmentDate: '',
      operationsAlignmentStatus: 'yes',
      legalReviewStatus: 'reviewed',
    },
    constitutionalAmendments: [],
    registrations: [
      {
        id: NIVARA_IDS.registrationPan,
        registrationType: 'pan',
        registrationNumber: NIVARA_ISSUER.pan,
        issuingAuthority: 'Income Tax Department',
        legalNameOnRegistration: NIVARA_ISSUER.legalName,
        addressOnRegistration: `${NIVARA_ISSUER.registeredOfficeLine1}, ${NIVARA_ISSUER.registeredOfficeCity}`,
        issueDate: NIVARA_ISSUER.incorporationDate,
        effectiveDate: NIVARA_ISSUER.incorporationDate,
        expiryDate: '',
        currentStatus: 'active',
        previousRegistrationNumber: '',
        updatedAfterNameChange: 'not-applicable',
        updatedAfterOfficeChange: 'not-applicable',
      },
      {
        id: NIVARA_IDS.registrationUdyam,
        registrationType: 'udyam',
        registrationNumber: NIVARA_ISSUER.udyam,
        issuingAuthority: 'Ministry of MSME',
        legalNameOnRegistration: NIVARA_ISSUER.legalName,
        addressOnRegistration: '',
        issueDate: '2020-04-15',
        effectiveDate: '2020-04-15',
        expiryDate: '',
        currentStatus: 'active',
        previousRegistrationNumber: '',
        updatedAfterNameChange: 'not-applicable',
        updatedAfterOfficeChange: 'not-applicable',
      },
    ],
    confirmations: {
      allFormerNamesDisclosed: true,
      allCompanyClassChangesDisclosed: true,
      allRegisteredOfficeChangesDisclosed: true,
      currentMoaWillBeProvided: true,
      currentAoaWillBeProvided: true,
      mainObjectsReflectCurrentBusiness: true,
      registrationsUseCurrentLegalName: true,
      noMaterialCorporateEventOmitted: true,
      authorisedRepresentativeDeclaration: true,
    },
  } as unknown as CompanyIncorporationSessionData;
}

// Reference for cross-workstream consistency tests
export const NIVARA_COMPANY_INCORPORATION_SNAPSHOT = {
  legalName: NIVARA_ISSUER.legalName,
  cin: NIVARA_ISSUER.cin,
  promoters: [NIVARA_PEOPLE.promoter1.name, NIVARA_PEOPLE.promoter2.name],
} as const;
