export const WORKSTREAM_GUIDANCE: Record<string, {
  keyRequirements: string[];
  commonIssues: string[];
  sebiReference: string;
  estimatedTime: string;
  relatedWorkstreams: string[];
}> = {
  'objects-of-issue': {
    keyRequirements: [
      'Define primary objective (capital raising)',
      'Specify secondary objectives',
      'Detail use of proceeds allocation',
      'Provide rationale for IPO size',
      'Link to company strategy',
    ],
    commonIssues: [
      'Vague or overly broad objectives',
      'Inconsistency with financial projections',
      'Insufficient detail on use of proceeds',
      'Lack of strategic rationale',
    ],
    sebiReference: 'Chapter II, Section A of SEBI Master Circular',
    estimatedTime: '3-5 business days',
    relatedWorkstreams: ['Company Overview', 'Financial Performance'],
  },
  'company-overview': {
    keyRequirements: [
      'Company incorporation and registration details',
      'Business operations overview',
      'Management structure',
      'Key milestones and history',
      'Current market position',
    ],
    commonIssues: [
      'Incomplete corporate history',
      'Missing key operational metrics',
      'Insufficient market context',
      'Unclear organizational structure',
    ],
    sebiReference: 'Chapter III, Item 1 of SEBI Master Circular',
    estimatedTime: '5-7 business days',
    relatedWorkstreams: ['Management & Governance', 'Business Model & Operations'],
  },
  'business-model': {
    keyRequirements: [
      'Revenue stream breakdown',
      'Customer segments and acquisition',
      'Value proposition',
      'Cost structure analysis',
      'Competitive positioning',
      'Business cycle and seasonality',
    ],
    commonIssues: [
      'Lack of quantified metrics',
      'Insufficient competitive analysis',
      'Missing revenue stream detail',
      'Unclear value proposition',
    ],
    sebiReference: 'Chapter III, Item 2 & 3 of SEBI Master Circular',
    estimatedTime: '7-10 business days',
    relatedWorkstreams: ['Financial Performance', 'Risk Factors'],
  },
  'financial-performance': {
    keyRequirements: [
      'Audited financial statements (3 years)',
      'Key financial metrics and ratios',
      'Revenue trends and growth analysis',
      'Profitability metrics',
      'Working capital management',
      'Cash flow analysis',
    ],
    commonIssues: [
      'Incomplete audit reports',
      'Inconsistent metrics',
      'Missing reconciliations',
      'Inadequate trend analysis',
    ],
    sebiReference: 'Chapter IX of SEBI Master Circular',
    estimatedTime: '10-14 business days',
    relatedWorkstreams: ['Objects of the Issue', 'Risk Factors'],
  },
  'management-team': {
    keyRequirements: [
      'Director and senior management profiles',
      'Qualifications and experience',
      'Compensation structure',
      'Related party transactions',
      'Board committee composition',
      'Corporate governance policies',
    ],
    commonIssues: [
      'Incomplete director disclosures',
      'Missing qualification details',
      'Inadequate governance documentation',
      'Related party transaction clarity',
    ],
    sebiReference: 'Chapter V & X of SEBI Master Circular',
    estimatedTime: '6-8 business days',
    relatedWorkstreams: ['Legal & Compliance', 'Related Party Transactions'],
  },
  'legal-compliance': {
    keyRequirements: [
      'Certificate of Incorporation',
      'Current registered address proof',
      'Regulatory registrations (GST, IEC, etc.)',
      'Compliance with statutes',
      'Material contracts and agreements',
      'Pending litigation status',
    ],
    commonIssues: [
      'Expired compliance certificates',
      'Missing regulatory approvals',
      'Unresolved litigation',
      'Incomplete contract documentation',
    ],
    sebiReference: 'Chapter VIII of SEBI Master Circular',
    estimatedTime: '8-10 business days',
    relatedWorkstreams: ['Company Overview', 'Material Contracts'],
  },
  'risk-factors': {
    keyRequirements: [
      'Business and operational risks',
      'Financial and market risks',
      'Regulatory and compliance risks',
      'Mitigation strategies for each risk',
      'Industry-specific risks',
      'Risk rating and severity assessment',
    ],
    commonIssues: [
      'Generic or boilerplate risk statements',
      'Insufficient mitigation strategies',
      'Missing industry-specific risks',
      'Inadequate quantification of impact',
    ],
    sebiReference: 'Chapter VII of SEBI Master Circular',
    estimatedTime: '7-9 business days',
    relatedWorkstreams: ['Business Model & Operations', 'Financial Performance'],
  },
  'capitalisation': {
    keyRequirements: [
      'Share capital structure',
      'Shareholding pattern',
      'Authorized vs issued capital',
      'Share class details and rights',
      'Warrant or convertible security details',
      'Post-IPO shareholding pattern',
    ],
    commonIssues: [
      'Unclear share class hierarchy',
      'Incomplete shareholding documentation',
      'Missing convertible details',
      'Ambiguous voting rights',
    ],
    sebiReference: 'Chapter VI of SEBI Master Circular',
    estimatedTime: '5-7 business days',
    relatedWorkstreams: ['Company Overview', 'Related Party Transactions'],
  },
  'pledging-restrictions': {
    keyRequirements: [
      'Pledged share documentation',
      'Share restriction declarations',
      'Lock-in period commitment',
      'Promoter undertakings',
      'Escrow arrangements if any',
      'Post-IPO restrictions clarity',
    ],
    commonIssues: [
      'Unclear pledge terms',
      'Missing undertakings',
      'Conflicting lock-in statements',
      'Incomplete escrow documentation',
    ],
    sebiReference: 'Chapter VI, Item 3 of SEBI Master Circular',
    estimatedTime: '4-5 business days',
    relatedWorkstreams: ['Capitalization & Shareholding'],
  },
  'material-contracts': {
    keyRequirements: [
      'Key supplier and customer contracts',
      'Facility/lease agreements',
      'Strategic partnership agreements',
      'Credit facility documentation',
      'Major distribution agreements',
      'Technology or IP licensing',
    ],
    commonIssues: [
      'Missing critical contracts',
      'Unsigned or draft contracts',
      'Unclear contract terms',
      'Missing termination clauses',
    ],
    sebiReference: 'Schedules to DRHP',
    estimatedTime: '8-10 business days',
    relatedWorkstreams: ['Legal & Compliance', 'Business Model & Operations'],
  },
  'related-party-transactions': {
    keyRequirements: [
      'All related party transaction details',
      'Transaction rationale and terms',
      'Board approval documentation',
      'Related party relationship disclosure',
      'Price reasonableness assessment',
      'Post-IPO policy on RPTs',
    ],
    commonIssues: [
      'Incomplete related party definitions',
      'Missing transaction documentation',
      'Inadequate arm&apos;s length justification',
      'Unclear pricing methodology',
    ],
    sebiReference: 'Chapter X, Item 4 of SEBI Master Circular',
    estimatedTime: '7-9 business days',
    relatedWorkstreams: ['Management & Governance', 'Legal & Compliance'],
  },
  'disclosure-requirements': {
    keyRequirements: [
      'Additional statutory disclosures',
      'Group company structure',
      'Pending regulatory actions',
      'Contingent liabilities',
      'Subsequent events disclosure',
      'Miscellaneous compliance matters',
    ],
    commonIssues: [
      'Incomplete regulatory action disclosure',
      'Missing contingent liability details',
      'Vague subsequent events',
      'Inadequate subsidiary documentation',
    ],
    sebiReference: 'Various sections of SEBI Master Circular',
    estimatedTime: '6-8 business days',
    relatedWorkstreams: ['All workstreams'],
  },
};
